version: '3.7'

networks:
    application:
    web:

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/dev/nginx/Dockerfile
        volumes:
            - ./:/app
        networks:
            - web
        ports:
            - 80:80

    gunicorn:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/dev/gunicorn/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
        networks:
            - web
            - application

    postgres:
        image: postgres:13
        restart: unless-stopped
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/postgres:/var/lib/postgresql/data
        networks:
            - application
